// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAthC8wrkbRddewscTn_wvaejgMoT1Vf0',
    appId: '1:523960482922:web:fd6ad4e8f8b7610ecf9e13',
    messagingSenderId: '523960482922',
    projectId: 'basiccrud-f5a5e',
    authDomain: 'basiccrud-f5a5e.firebaseapp.com',
    storageBucket: 'basiccrud-f5a5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQFuNovz1DBqIK5PJJotqXYbkIaau9fU',
    appId: '1:523960482922:android:6353cbbc537da5f4cf9e13',
    messagingSenderId: '523960482922',
    projectId: 'basiccrud-f5a5e',
    storageBucket: 'basiccrud-f5a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmscidAY0AegIlFXRS0etS9_OxJ8wu7Ic',
    appId: '1:523960482922:ios:aeeb5fdcc41f9558cf9e13',
    messagingSenderId: '523960482922',
    projectId: 'basiccrud-f5a5e',
    storageBucket: 'basiccrud-f5a5e.appspot.com',
    iosClientId: '523960482922-h9epbrii26io61vr7c5kemd4tc8ucaeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.basiccrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmscidAY0AegIlFXRS0etS9_OxJ8wu7Ic',
    appId: '1:523960482922:ios:aeeb5fdcc41f9558cf9e13',
    messagingSenderId: '523960482922',
    projectId: 'basiccrud-f5a5e',
    storageBucket: 'basiccrud-f5a5e.appspot.com',
    iosClientId: '523960482922-h9epbrii26io61vr7c5kemd4tc8ucaeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.basiccrud',
  );
}
